--- #YAML:1.0
name: Regex-Iterator
version: 0.3
author:
  - Copyright (c) 2004,
  - Simon Wistow <simon@thegestalt.org>
  - Matt Lawrence <mattlaw@cpan.org>
abstract: provides an iterator interface to regexps
license: perl
requires:
  Test::More: 0
provides:
  Regex::Iterator:
    file: lib/Regex/Iterator.pm
    version: 0.3
generated_by: Module::Build version 0.25
